#season: <int>
# This for the season of the Bliss SMP
# RN it's only 3
#
#
#givegemonfirstjoin: <boolean>
# false = Don't give a player a gem when they first join
# true = Give a player a gem when they first join
#
season: 3
givegemonfirstjoin: false

