#season: <int>
#1-3
# 3 (Default)
# The season of Bliss SMP
#
#
#
#give_gem_on_first_join: <boolean>
# false = Don't give a player a gem when they first join (Default)
# true = Give a player a gem when they first join
#
#
#
#autoupdateseasonofgem: <boolean>
# false = Don't update the values of the player's gem when they join
# true = update the values of the player's gem when they join (Default)
#
#
#
#allow_gem_dropping: <boolean>
# false = Don't allow the player to drop their gem (Default)
# true = allow the player to drop their gem
#
#
#
#allow_gem_removing: <boolean>
# false = Don't allow the player to remove their gem from their inventory (Default)
# true = allow the player to remove their gem from their inventory
#
#
#
#texture_pack_loading: <boolean>
# false = Don't load the Bliss SMP texture pack
# true = load the Bliss SMP texture pack (Default)
#
#
#
#unload_player_cooldowns_on_leave: <boolean>
# false = Don't free the used memory by the player's cooldowns (Causes memory leaks AKA more memory usage)
# true = Free the used memory by the player's cooldowns (Strongly recommended) (Default)
#
#
#
#metrics: <boolean>
# false = Don't use bStats metrics
# true = Use bStats metrics (Default)
#
season: 3
give_gem_on_first_join: false
allow_gem_dropping: false
allow_gem_removing: false
texture_pack_loading: true
unload_player_cooldowns_on_leave: true
metrics: true