name: BlissGems
version: 'dev'
main: com.hyperdondon.blissgemsremake.blissgems
description: §x§f§f§e§4§a§b§lBlissGemsRemake §fby §4Hyper_Dondon §band §0Cupm §f(Original by Pro4D)
api-version: '1.17'
authors:
  - Hyper_Dondon
  - Cupm
commands:
  blissgems:
    aliases: bliss
    description: Main command for BlissGems
    usage: /<command>

  progression:
    description: Command for progression
    usage: /<command>

  progobsidian:
    description: Gives the player enchanted obsidian
    usage: /<command>