name: BlissGems
version: '1.2.1'
main: com.hyperdondon.blissgemsremake.blissgems
description: §x§f§f§e§4§a§b§lBliss §7by Pro4D/aglerr
api-version: '1.19'
authors:
  - aglerr
  - Pro4D
commands:
  bliss:
    description: Main command for BlissGems
    usage: /<command>

  progression:
    description: Command for progression
    usage: /<command>

  progobsidian:
    description: Gives the player enchanted obsidian
    usage: /<command>